---
title: "Применение геоинформационных инструментов для работы с большими данными при анализе пространственного распределения пожаров"
date: 2021-06
date-format: "MMMM YYYY"
comments: false
categories: [статья, R]
csl: gost-r-7-0-5-2008-numeric-alphabetical.csl
lang: ru
author:
  - name: Е.Н. Матеров
    orcid: 0000-0002-3916-0613
    email: materov@gmail.com
    affiliations:
      - name: ФГБОУ ВО Сибирская пожарно-спасательная академия ГПС МЧС России      
  - name: С.В. Бабёнышев
    orcid: 0000-0002-4298-2036
    email: sergei.babyonyshev@gmail.com
    affiliation: ФГБОУ ВО Сибирская пожарно-спасательная академия ГПС МЧС России
  - name: О.С. Малютин
    orcid: 0000-0001-5543-1324
    email: obsidian-pb@mail.ru
    affiliation: ФГБОУ ВО Сибирская пожарно-спасательная академия ГПС МЧС России
  - name: Г.М. Бойко  
    affiliation: ФГБОУ ВО Сибирская пожарно-спасательная академия ГПС МЧС России
  
citation: 
  type: article-journal
  title: Применение геоинформационных инструментов для работы с большими данными при анализе пространственного распределения пожаров
  volume: 21
  number: 2
  issued: 2021
  container-title: Сибирский пожарно-спасательный вестник
  page: 70-77
  keyword: географические данные, район выезда
  url: http://vestnik.sibpsa.ru/
  #url: http://vestnik.sibpsa.ru/?p=3004
---

В статье рассмотрены возможности языков программирования Python и R в применении к геокодингу и анализу географических данных, связанных с пожарами и их последствиями. В работе рассмотрены: нанесение на статические и интерактивные географические карты исходных данных по пожарам, графика плотности пожаров, данных по времени прибытия подразделений, а также построение зон транспортной доступности и оптимальных маршрутов. Использованные аналитические инструменты могут быть полезны при определении порядка привлечения сил и средств подразделений пожарно-спасательных гарнизонов, в частности, при разработке планов привлечения и расписаний выездов сил и средств гарнизонов для тушения пожаров. Приведенная в работе процедура анализа может быть использована, с учетом специфики, практически для любого населенного пункта Российской Федерации.