---
title: "Ретроспективный анализ лесных пожаров в Красноярском крае с использованием науки о данных и метод машинного обучения"
date: 2023-12
date-format: "MMMM YYYY"
comments: false
categories: [статья, R]
csl: gost-r-7-0-5-2008-numeric-alphabetical.csl
lang: ru
author:
  - name: С.В. Бабёнышев
    orcid: 0000-0002-4298-2036
    email: sergei.babyonyshev@gmail.com
    affiliation: ФГБОУ ВО Сибирская пожарно-спасательная академия ГПС МЧС России
  - name: Е.Н. Матеров
    orcid: 0000-0002-3916-0613
    email: materov@gmail.com
    affiliations: ФГБОУ ВО Сибирская пожарно-спасательная академия ГПС МЧС России
  - name: Т.А. Миловидова
    orcid: 0000-0003-0513-2881
    email: tanya-1972@list.ru
    affiliation: ФГБОУ ВО Сибирская пожарно-спасательная академия ГПС МЧС России     
  
citation: 
  type: article-journal
  title: Ретроспективный анализ лесных пожаров в Красноярском крае с использованием науки о данных и метод машинного обучения
  volume: 31
  number: 4
  issued: 2023
  container-title: Сибирский пожарно-спасательный вестник
  page: 148-159
  keyword: лесные пожары, машинное обучение, моделирование
  url: http://vestnik.sibpsa.ru/
  #url: https://vestnik.sibpsa.ru/?page_id=5812
---

В статье анализируются данные о лесных пожарах в Красноярском крае за период 2011-2023 гг. с учетом их географического распределения. В работе рассмотрены: (1) разведочный анализ данных о пожарах, включая антропогенное воздействие на пожарную активность и изменений в пожарах с течением лет; (2) построение модели машинного обучения, которая предсказывает, является ли термоточка критической, т.е. находится ближе 5 км от населенного пункта или площадь пожара более 200 га. Новизна работы заключается в эффективном использовании языка программирования R, наделенного расширенными возможностями для анализа данных, моделирования методами машинного обучения и визуализации. Использование методов обработки данных, рассмотренных в статье, может повысить точность обнаружения и прогнозирования изменений пожарной активности, последующего мониторинга и крупномасштабного управления пожаротушением. Подходы, разобранные в статье, могут быть применены и к другим регионам Российской Федерации.