---
title: "Анализ пожарной и техносферной безопасности городской среды г. Красноярска с применением геопространственных инструментов"
date: 2021-12
date-format: "MMMM YYYY"
comments: false
categories: [статья, R]
csl: gost-r-7-0-5-2008-numeric-alphabetical.csl
lang: ru
author:
  - name: Е.Н. Матеров
    orcid: 0000-0002-3916-0613
    email: materov@gmail.com
    affiliations: ФГБОУ ВО Сибирская пожарно-спасательная академия ГПС МЧС России      
  - name: С.В. Бабёнышев
    orcid: 0000-0002-4298-2036
    email: sergei.babyonyshev@gmail.com
    affiliation: ФГБОУ ВО Сибирская пожарно-спасательная академия ГПС МЧС России
  - name: О.С. Малютин
    orcid: 0000-0001-5543-1324
    email: obsidian-pb@mail.ru
    affiliation: ФГБОУ ВО Сибирская пожарно-спасательная академия ГПС МЧС России
  - name: М.В. Елфимова  
    affiliation: ФГБОУ ВО Сибирская пожарно-спасательная академия ГПС МЧС России
  
citation: 
  type: article-journal
  title: Анализ пожарной и техносферной безопасности городской среды г. Красноярска с применением геопространственных инструментов
  volume: 23
  number: 4
  issued: 2021
  container-title: Сибирский пожарно-спасательный вестник
  page: 128-136
  keyword: геопространственный анализ, источники противопожарного водоснабжения, районы выезда
  url: http://vestnik.sibpsa.ru/
  #url: http://vestnik.sibpsa.ru/?p=3231
---

В статье рассмотрены возможности применения современных открытых геоинформационных инструментов к анализу географических данных в некоторых проблемах техносферной и пожарной безопасности. В частности, в вопросах связанных с оценкой зон достижимости социально-значимых объектов, оценкой влияния плотности застройки на распределение пожаров, а также анализом источников противопожарного водоснабжения в городской среде. Основные расчеты выполнены с использованием языка программирования R. Применяемые инструменты могут быть полезными для планирования надзорных мероприятий, а также при оценке сил и средств гарнизонов для организации тушения пожаров. Результаты, приведенные в работе, получены для города Красноярска, однако подобные подходы могут быть использованы для вычислений и визуализации аналогичного рода для любого населенного пункта Российской Федерации.
